# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence_generator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sequence_generator.proto',
  package='sequenceNumber',
  syntax='proto3',
  serialized_pb=_b('\n\x18sequence_generator.proto\x12\x0esequenceNumber\"\x12\n\x10q_SequenceNumber\"*\n\x10p_SequenceNumber\x12\x16\n\x0esequenceNumber\x18\x01 \x01(\t2y\n\x17SequenceNumberGenerator\x12^\n\x16GenerateSequenceNumber\x12 .sequenceNumber.q_SequenceNumber\x1a .sequenceNumber.p_SequenceNumber\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_Q_SEQUENCENUMBER = _descriptor.Descriptor(
  name='q_SequenceNumber',
  full_name='sequenceNumber.q_SequenceNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=62,
)


_P_SEQUENCENUMBER = _descriptor.Descriptor(
  name='p_SequenceNumber',
  full_name='sequenceNumber.p_SequenceNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='sequenceNumber.p_SequenceNumber.sequenceNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['q_SequenceNumber'] = _Q_SEQUENCENUMBER
DESCRIPTOR.message_types_by_name['p_SequenceNumber'] = _P_SEQUENCENUMBER

q_SequenceNumber = _reflection.GeneratedProtocolMessageType('q_SequenceNumber', (_message.Message,), dict(
  DESCRIPTOR = _Q_SEQUENCENUMBER,
  __module__ = 'sequence_generator_pb2'
  # @@protoc_insertion_point(class_scope:sequenceNumber.q_SequenceNumber)
  ))
_sym_db.RegisterMessage(q_SequenceNumber)

p_SequenceNumber = _reflection.GeneratedProtocolMessageType('p_SequenceNumber', (_message.Message,), dict(
  DESCRIPTOR = _P_SEQUENCENUMBER,
  __module__ = 'sequence_generator_pb2'
  # @@protoc_insertion_point(class_scope:sequenceNumber.p_SequenceNumber)
  ))
_sym_db.RegisterMessage(p_SequenceNumber)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class SequenceNumberGeneratorStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateSequenceNumber = channel.unary_unary(
        '/sequenceNumber.SequenceNumberGenerator/GenerateSequenceNumber',
        request_serializer=q_SequenceNumber.SerializeToString,
        response_deserializer=p_SequenceNumber.FromString,
        )


class SequenceNumberGeneratorServicer(object):

  def GenerateSequenceNumber(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SequenceNumberGeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateSequenceNumber': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateSequenceNumber,
          request_deserializer=q_SequenceNumber.FromString,
          response_serializer=p_SequenceNumber.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sequenceNumber.SequenceNumberGenerator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaSequenceNumberGeneratorServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def GenerateSequenceNumber(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaSequenceNumberGeneratorStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def GenerateSequenceNumber(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GenerateSequenceNumber.future = None


def beta_create_SequenceNumberGenerator_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('sequenceNumber.SequenceNumberGenerator', 'GenerateSequenceNumber'): q_SequenceNumber.FromString,
  }
  response_serializers = {
    ('sequenceNumber.SequenceNumberGenerator', 'GenerateSequenceNumber'): p_SequenceNumber.SerializeToString,
  }
  method_implementations = {
    ('sequenceNumber.SequenceNumberGenerator', 'GenerateSequenceNumber'): face_utilities.unary_unary_inline(servicer.GenerateSequenceNumber),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_SequenceNumberGenerator_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('sequenceNumber.SequenceNumberGenerator', 'GenerateSequenceNumber'): q_SequenceNumber.SerializeToString,
  }
  response_deserializers = {
    ('sequenceNumber.SequenceNumberGenerator', 'GenerateSequenceNumber'): p_SequenceNumber.FromString,
  }
  cardinalities = {
    'GenerateSequenceNumber': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'sequenceNumber.SequenceNumberGenerator', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
